// package pl.pkg2;


// import pl.pkg2.adminClass;
// import javax.swing.JOptionPane;


// public class adminMain extends javax.swing.JFrame {

//     /**
//      * Creates new form adminMain
//      */
//     public adminMain() {
//         initComponents();
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jLabel1 = new javax.swing.JLabel();
//         jButton1 = new javax.swing.JButton();
//         jLabel2 = new javax.swing.JLabel();
//         jLabel3 = new javax.swing.JLabel();
//         jLabel4 = new javax.swing.JLabel();
//         jLabel5 = new javax.swing.JLabel();
//         jButton2 = new javax.swing.JButton();
//         idField = new javax.swing.JTextField();
//         RoleNumberField = new javax.swing.JTextField();
//         NewStringField = new javax.swing.JTextField();
//         FieldNumberField = new javax.swing.JTextField();
//         jLabel6 = new javax.swing.JLabel();
//         jLabel7 = new javax.swing.JLabel();
//         jLabel8 = new javax.swing.JLabel();
//         jLabel9 = new javax.swing.JLabel();
//         jLabel10 = new javax.swing.JLabel();
//         jLabel11 = new javax.swing.JLabel();
//         jLabel12 = new javax.swing.JLabel();
//         jLabel13 = new javax.swing.JLabel();
//         jButton3 = new javax.swing.JButton();
//         jLabel14 = new javax.swing.JLabel();
//         jLabel15 = new javax.swing.JLabel();
//         jLabel16 = new javax.swing.JLabel();
//         jLabel17 = new javax.swing.JLabel();
//         jTextField3 = new javax.swing.JTextField();
//         jLabel18 = new javax.swing.JLabel();
//         Label = new javax.swing.JLabel();
//         idfLabel = new javax.swing.JTextField();
//         jButton4 = new javax.swing.JButton();

//         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

//         jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
//         jLabel1.setText("Edit :-");

//         jButton1.setText("ADD");
//         jButton1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton1ActionPerformed(evt);
//             }
//         });

//         jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel2.setText("1- SP");

//         jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel3.setText("2- PM");

//         jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel4.setText("3- Customer");

//         jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel5.setText("4- Admin");

//         jButton2.setText("UPDATE");
//         jButton2.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton2ActionPerformed(evt);
//             }
//         });

//         jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel6.setText("1- Name");

//         jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel7.setText("2- Phone");

//         jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel8.setText("3- Email");

//         jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel9.setText("4- Password");

//         jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel10.setText("ID");

//         jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel11.setText("Role Number");

//         jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel12.setText("New String");

//         jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel13.setText("Field Number");

//         jButton3.setText("DELETE");
//         jButton3.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton3ActionPerformed(evt);
//             }
//         });

//         jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel14.setText("4- Admin");

//         jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel15.setText("1- SP");

//         jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel16.setText("2- PM");

//         jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel17.setText("3- Customer");

//         jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jLabel18.setText("Role Number");

//         Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         Label.setText("ID");

//         jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
//         jButton4.setText("Send Request to PM");

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//         getContentPane().setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(layout.createSequentialGroup()
//                         .addComponent(jLabel1)
//                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                         .addGap(0, 51, Short.MAX_VALUE)
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                             .addGroup(layout.createSequentialGroup()
//                                 .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                                 .addComponent(jLabel11)
//                                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                     .addGroup(layout.createSequentialGroup()
//                                                         .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                         .addGap(7, 7, 7))
//                                                     .addGroup(layout.createSequentialGroup()
//                                                         .addGap(5, 5, 5)
//                                                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                                                 .addGap(15, 15, 15)
//                                                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                                     .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                     .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                                 .addGap(15, 15, 15))
//                                                             .addGroup(layout.createSequentialGroup()
//                                                                 .addGap(6, 6, 6)
//                                                                 .addComponent(jLabel14))
//                                                             .addComponent(jLabel17)))))
//                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                                     .addComponent(jLabel18)
//                                                     .addGap(1, 1, 1))
//                                                 .addGroup(layout.createSequentialGroup()
//                                                     .addGap(6, 6, 6)
//                                                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                         .addGroup(layout.createSequentialGroup()
//                                                             .addGap(6, 6, 6)
//                                                             .addComponent(jLabel5))
//                                                         .addComponent(jLabel4)
//                                                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                                 .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                 .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                             .addGap(16, 16, 16))))))
//                                         .addGap(23, 23, 23))
//                                     .addGroup(layout.createSequentialGroup()
//                                         .addGap(30, 30, 30)
//                                         .addComponent(RoleNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                         .addGap(31, 31, 31)))
//                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                     .addGroup(layout.createSequentialGroup()
//                                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                             .addComponent(jLabel12)
//                                             .addComponent(NewStringField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                         .addGap(18, 18, 18)
//                                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                             .addGroup(layout.createSequentialGroup()
//                                                 .addGap(6, 6, 6)
//                                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                     .addGroup(layout.createSequentialGroup()
//                                                         .addGap(6, 6, 6)
//                                                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                             .addComponent(jLabel8)
//                                                             .addComponent(jLabel7)
//                                                             .addComponent(jLabel6)))
//                                                     .addComponent(jLabel9)
//                                                     .addComponent(FieldNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                             .addComponent(jLabel13)))
//                                     .addGroup(layout.createSequentialGroup()
//                                         .addGap(62, 62, 62)
//                                         .addComponent(jButton4)))
//                                 .addGap(34, 34, 34))
//                             .addGroup(layout.createSequentialGroup()
//                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                     .addComponent(jButton2)
//                                     .addComponent(jButton1)
//                                     .addComponent(jButton3))
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                     .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                         .addComponent(idfLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                         .addComponent(Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                 .addGap(388, 388, 388))))))
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jLabel1)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
//                 .addComponent(jButton1)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(layout.createSequentialGroup()
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
//                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                 .addComponent(jButton2)
//                                 .addComponent(jLabel13)
//                                 .addComponent(jLabel11)))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(RoleNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(NewStringField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(FieldNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                     .addComponent(jLabel10))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(layout.createSequentialGroup()
//                         .addComponent(jLabel6)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jLabel7)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jLabel8)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jLabel9)
//                         .addGap(21, 21, 21)
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jButton3)
//                             .addGroup(layout.createSequentialGroup()
//                                 .addGap(26, 26, 26)
//                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                     .addComponent(idfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                     .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                     .addComponent(jButton4)))
//                             .addComponent(Label))
//                         .addGap(10, 10, 10)
//                         .addComponent(jLabel15)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jLabel16)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jLabel17)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(layout.createSequentialGroup()
//                         .addComponent(jLabel2)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jLabel3)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jLabel4)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addComponent(jLabel18)))
//                 .addContainerGap())
//         );

//         pack();
//     }// </editor-fold>//GEN-END:initComponents

//     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//         int x = Integer.parseInt(idField.getText());
//         int y = Integer.parseInt(RoleNumberField.getText());
//         String role, number;

//         switch (y) {
//             case 1:
//                 role = "SP";
//                 break;
//             case 2:
//                 role = "PM";
//                 break;
//             case 3:
//                 role = "Customer";
//                 break;
//             case 4:
//                 role = "Admin";
//                 break;
//             default:
//                 JOptionPane.showMessageDialog(this, "Invalid role number entered!", "Error", JOptionPane.ERROR_MESSAGE);
//                 return; // Exit the method if role number is invalid
//         } 

//             String newString = NewStringField.getText();

//             int z = Integer.parseInt(FieldNumberField.getText());

//             adminClass ss = new adminClass();

//             int result = ss.updateUserById (x, role, newString, z);

//             if (result == -1) {
//                 JOptionPane.showMessageDialog(this, "File not found or user not updated.", "Error", JOptionPane.ERROR_MESSAGE);
//             }
//             else {
//                 JOptionPane.showMessageDialog(this, "User updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
//             }    
//     }


//     }//GEN-LAST:event_jButton2ActionPerformed

//     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//         adminClass ca = new adminClass();
//         ca.setVisible(true);
//         ca.setLocationRelativeTo(null);
//         this.setVisible(false);
    
//     }//GEN-LAST:event_jButton1ActionPerformed

//     private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//         String x = idfLabel.getText();
//         int y = Integer.parseInt(jTextField3.getText());

//         String role = "";
//                 switch(y){
//             case 1 : role = "SP";
//                 break;
//             case 2 : role = "PM";
//                 break;
//             case 3 : role = "Customer";
//                 break;
//             case 4 : role = "Admin";
//                 break;
//         }
                
//         adminClass aa = new adminClass();
//         aa.deleteUserById(x,role);
//     }//GEN-LAST:event_jButton3ActionPerformed


//     public static void main(String args[]) {
//     /* Set the Nimbus look and feel */
//     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//          * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//      */
//     try {
//         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//             if ("Nimbus".equals(info.getName())) {
//                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                 break;
//             }
//         }
//     } catch (ClassNotFoundException ex) {
//         java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//     } catch (InstantiationException ex) {
//         java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//     } catch (IllegalAccessException ex) {
//         java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//         java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//     }
//     //</editor-fold>

//     /* Create and display the form */
//     java.awt.EventQueue.invokeLater(new Runnable() {
//         public void run() {
//             new adminMain().setVisible(true);
//         }
//     });
// }

//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.JTextField FieldNumberField;
//     private javax.swing.JLabel Label;
//     private javax.swing.JTextField NewStringField;
//     private javax.swing.JTextField RoleNumberField;
//     private javax.swing.JTextField idField;
//     private javax.swing.JTextField idfLabel;
//     private javax.swing.JButton jButton1;
//     private javax.swing.JButton jButton2;
//     private javax.swing.JButton jButton3;
//     private javax.swing.JButton jButton4;
//     private javax.swing.JLabel jLabel1;
//     private javax.swing.JLabel jLabel10;
//     private javax.swing.JLabel jLabel11;
//     private javax.swing.JLabel jLabel12;
//     private javax.swing.JLabel jLabel13;
//     private javax.swing.JLabel jLabel14;
//     private javax.swing.JLabel jLabel15;
//     private javax.swing.JLabel jLabel16;
//     private javax.swing.JLabel jLabel17;
//     private javax.swing.JLabel jLabel18;
//     private javax.swing.JLabel jLabel2;
//     private javax.swing.JLabel jLabel3;
//     private javax.swing.JLabel jLabel4;
//     private javax.swing.JLabel jLabel5;
//     private javax.swing.JLabel jLabel6;
//     private javax.swing.JLabel jLabel7;
//     private javax.swing.JLabel jLabel8;
//     private javax.swing.JLabel jLabel9;
//     private javax.swing.JTextField jTextField3;
//     // End of variables declaration//GEN-END:variables



package pl.pkg2;

import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class adminMain extends JFrame {
    // UI Components
    private JTextField idField, newStringField, deleteIdField, requestIdField;
    private JButton updateButton, deleteButton, backButton, sendRequestButton;
    private JComboBox<String> roleComboBox, fieldComboBox, deleteRoleComboBox;

    public adminMain() {
        initComponents();
    }

    private void initComponents() {
        // Set up the frame
        setTitle("Admin Management System");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(500, 600);
        setLocationRelativeTo(null);
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);

        // Title
        JLabel titleLabel = new JLabel("Admin Management System");
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 20));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        add(titleLabel, gbc);

        // Update Section
        gbc.gridwidth = 1;
        gbc.gridy = 1;
        gbc.gridx = 0;
        add(new JLabel("User ID:"), gbc);
        
        gbc.gridx = 1;
        idField = new JTextField(15);
        add(idField, gbc);

        gbc.gridy = 2;
        gbc.gridx = 0;
        add(new JLabel("Role:"), gbc);
        
        gbc.gridx = 1;
        String[] roles = {"SP", "PM", "Customer", "Admin"};
        roleComboBox = new JComboBox<>(roles);
        add(roleComboBox, gbc);

        gbc.gridy = 3;
        gbc.gridx = 0;
        add(new JLabel("Field to Update:"), gbc);
        
        gbc.gridx = 1;
        String[] fields = {"Name", "Phone", "Email", "Password"};
        fieldComboBox = new JComboBox<>(fields);
        add(fieldComboBox, gbc);

        gbc.gridy = 4;
        gbc.gridx = 0;
        add(new JLabel("New Value:"), gbc);
        
        gbc.gridx = 1;
        newStringField = new JTextField(15);
        add(newStringField, gbc);

        // Update Button
        gbc.gridy = 5;
        gbc.gridx = 1;
        updateButton = new JButton("Update User");
        updateButton.addActionListener((ActionEvent evt) -> {
            updateUser();
        });
        add(updateButton, gbc);

        // Delete Section
        gbc.gridy = 6;
        gbc.gridx = 0;
        add(new JLabel("Delete User ID:"), gbc);
        
        gbc.gridx = 1;
        deleteIdField = new JTextField(15);
        add(deleteIdField, gbc);

        gbc.gridy = 7;
        gbc.gridx = 0;
        add(new JLabel("Delete User Role:"), gbc);
        

        
        gbc.gridx = 1;
        String[] role = {"SP", "PM", "Customer", "Admin"};
        deleteRoleComboBox = new JComboBox<>(role);
         add(deleteRoleComboBox, gbc);
        // Delete Button
        gbc.gridy = 8;
        gbc.gridx = 1;
        deleteButton = new JButton("Delete User");
        deleteButton.addActionListener((ActionEvent evt) -> {
            deleteUser();
        });
        add(deleteButton, gbc);

    // Add Request Section
        gbc.gridy = 9;
        gbc.gridx = 0;
        add(new JLabel("Customer ID:"), gbc);
        
        gbc.gridx = 1;
        requestIdField = new JTextField(15);
        add(requestIdField, gbc);

        // Send Request Button
        gbc.gridy = 10;
        gbc.gridx = 1;
        sendRequestButton = new JButton("Send Request to PM");
        sendRequestButton.addActionListener((ActionEvent evt) -> {
            sendRequestToPM();
        });
        add(sendRequestButton, gbc);   
        
        // Back Button
        gbc.gridy = 11;
        gbc.gridx = 1;
        backButton = new JButton("Back to Main");
        backButton.addActionListener((ActionEvent evt) -> {
            goBack();
        });
        add(backButton, gbc);
    }

        private void sendRequestToPM() {
        try {
            if (requestIdField.getText().trim().isEmpty()) {
                showError("Customer ID cannot be empty");
                return;
            }

            int id = Integer.parseInt(requestIdField.getText().trim());
            adminClass admin = new adminClass();
            int result = admin.sendCustomerRequestToPM(id);

            if (result == 1) {
                showSuccess("Request sent successfully to PM!");
                requestIdField.setText(""); // Clear the field
            } else {
                showError("Failed to send request. Please check the customer ID.");
            }
        } catch (NumberFormatException e) {
            showError("Invalid Customer ID. Please enter a valid number.");
        } catch (Exception e) {
            showError("An error occurred: " + e.getMessage());
        }
    }
    
    private void updateUser() {
        try {
            // Validate inputs
            if (idField.getText().trim().isEmpty()) {
                showError("User ID cannot be empty");
                return;
            }

            int userId = Integer.parseInt(idField.getText().trim());
            String role = (String) roleComboBox.getSelectedItem();
            String field = (String) fieldComboBox.getSelectedItem();
            String newValue = newStringField.getText().trim();

            // Validate new value based on field
            if (newValue.isEmpty()) {
                showError("New value cannot be empty");
                return;
            }

            // Call update method from AdminClass
            adminClass adminClass = new adminClass();
            int result = adminClass.updateUserById(userId, role, newValue, getFieldNumber(field));

            if (result == 1) {
                showSuccess("User updated successfully!");
                clearUpdateFields();
            } else {
                showError("Failed to update user. Please check the details.");
            }
        } catch (NumberFormatException e) {
            showError("Invalid User ID. Please enter a valid number.");
        } catch (Exception e) {
            showError("An error occurred: " + e.getMessage());
        }
    }

private void deleteUser() {
    try {
        // Validate inputs
        if (deleteIdField.getText().trim().isEmpty()) {
            showError("User ID cannot be empty");
            return;
        }

        String userId = deleteIdField.getText().trim();
//         String role = (String) roleComboBox.getSelectedItem();
       String role = (String) deleteRoleComboBox.getSelectedItem();


        // Call delete method from AdminClass
        adminClass a = new adminClass();
        int result = a.deleteUserById(userId, role);

        switch (result) {
            case 1 -> {
                showSuccess("User deleted successfully!");
                clearDeleteFields();
            }
            case -1 -> showError("User not found or could not be deleted. Please check the details.");
            default -> showError("An unexpected error occurred while deleting the user.");
        }
    } catch (Exception e) {
        showError("An error occurred: " + e.getMessage());
    }
}


    private void goBack() {
        // Implement navigation back to the previous screen
        // This is a placeholder and should be replaced with actual navigation logic
        JOptionPane.showMessageDialog(this, "Returning to previous screen");
        this.dispose();
    }

    private int getFieldNumber(String field) {
        return switch (field) {
            case "Name" -> 1;
            case "Phone" -> 2;
            case "Email" -> 3;
            case "Password" -> 4;
            default -> 0;
        };
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    private void showSuccess(String message) {
        JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    private void clearUpdateFields() {
        idField.setText("");
        newStringField.setText("");
    }

    private void clearDeleteFields() {
        deleteIdField.setText("");
    }

    public static void main(String args[]) {
        // Set the Nimbus look and feel
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(adminMain.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Create and show the form
        SwingUtilities.invokeLater(() -> {
            new adminMain().setVisible(true);
        });
    }
}
